#!/bin/env sh

PATH=/usr/bin:/usr/sbin:/bin:/sbin

# Must have sysfs mounted for udevtrigger to function.
mount -n -t sysfs sysfs /sys || true
    
# Ideally devtmpfs will be mounted by kernel, we can mount here anyway:
mount -n -t devtmpfs tmpfs /dev || true
mkdir -p /dev/pts /dev/shm || true
mount -n -t tmpfs -o nodev,nosuid tmpfs /dev/shm || true
mount -n -t devpts -o gid=5 devpts /dev/pts || true

# /run, and various directories within it
mount -n -t tmpfs -o mode=775 tmpfs /run || true
mkdir -p /run/lock /run/udev
    
# "hidepid=1" doesn't appear to take effect on first mount of /proc,
# so we mount it and then remount:
mount -n -t proc -o hidepid=1 proc /proc
mount -n -t proc -o remount,hidepid=1 proc /proc

if [ -d /sys/kernel/security ]; then
  mount -n -t securityfs securityfs /sys/kernel/security || :
fi

if [ -d /sys/firmware/efi/efivars ]; then
  mount -o nosuid,noexec,nodev -t efivarfs efivarfs /sys/firmware/efi/efivars || :
fi
